### ISSUE TITLE
W3C Web Annotation Data Model

### ISSUE THREAD

**Issue by altugcagri** [altugcagri/boun-swe-574#3]
**Describe the research you'd like**
Study the recommended specifications for W3C Web Annotation Data Model (https:
//www.w3.org/TR/annotation-model/)

Create a wiki documentation summarizing the content.

**Comment by gulsahcoskun** [comment]
Web Annotation Data Model research has been completed. It took 5 hours. 
Related wiki page : https://github.com/altugcagri/boun-swe-574/wiki/W3C-Web-Annotation-Data-Model-Research
