### ISSUE TITLE
Wikidata 

### ISSUE THREAD

**Issue by altugcagri** [altugcagri/boun-swe-574#4]
**Describe the research you'd like**
Study the recommended specifications for Wikidata (https://www.wikidata.
org)

Create a wiki documentation summarizing the content.

**Comment by tallrye** [comment]
Both Wikidata and The MediaWiki API has been researched and the summary has been documented at [this wiki page.](https://github.com/altugcagri/boun-swe-574/wiki/Research:-Wikidata-and-WikiAPI)
