### ISSUE TITLE
oa motivation will be discussed

### ISSUE THREAD

**Issue by CihangirOzmus** [altugcagri/boun-swe-574#65]
@tallrye please, ask to @gulsahcoskun.

**Comment by CihangirOzmus** [comment]
motivation field will be added as same as comment field.

**Comment by gulsahcoskun** [comment]
Motivation field has been added to annotation.
Duration:1 hour

**Comment by CihangirOzmus** [comment]
Completed by Gulsah Coskun and Serhat Uzuncavdar.
